// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentSystem_WebApiDB.Data;

#nullable disable

namespace StudentSystem_WebApiDB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240401185040_updatedStudentTable")]
    partial class updatedStudentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentSystem_WebApiDB.Data.Models.Lector", b =>
                {
                    b.Property<int>("LectorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LectorID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LectorID");

                    b.ToTable("lector");
                });

            modelBuilder.Entity("StudentSystem_WebApiDB.Data.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LectorID")
                        .HasColumnType("int");

                    b.HasKey("StudentID");

                    b.HasIndex("LectorID");

                    b.ToTable("student");
                });

            modelBuilder.Entity("StudentSystem_WebApiDB.Data.Models.Student", b =>
                {
                    b.HasOne("StudentSystem_WebApiDB.Data.Models.Lector", "Lectors")
                        .WithMany("Students")
                        .HasForeignKey("LectorID");

                    b.Navigation("Lectors");
                });

            modelBuilder.Entity("StudentSystem_WebApiDB.Data.Models.Lector", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
